<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="SkiaSharp" Version="4.151.2" />

        <PackageReference Include="bblanchon.PDFium.Win32" Version="154.0.8035" Condition="$([MSBuild]::IsOsPlatform('Windows'))" />
        <PackageReference Include="bblanchon.PDFium.macOS" Version="154.0.8035" Condition="$([MSBuild]::IsOsPlatform('OSX'))"/>
        <PackageReference Include="bblanchon.PDFium.Linux" Version="154.0.8035" Condition="$([MSBuild]::IsOsPlatform('Linux'))"/>
    </ItemGroup>
</Project>
